# Generated by Django 3.1 on 2020-08-19 04:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 19, 4, 41, 18, 671800, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
